spring:
    application:
        name: beprepared
    datasource:
        url: jdbc:postgresql://localhost:5432/beprepared
        username: postgres
        password: JokingWill12345
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
    swagger-ui:
        tags-sorter: alpha